trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: none
  - pwsh: |
      Write-Host "##vso[task.setvariable variable=foo;isreadonly=True]foo"
      Write-Host "Foo: "
      Write-Host $Env:FOO
  - pwsh: |
      Write-Host "Foo: "
      Write-Host $Env:FOO
