trigger:
  - main

pool:
  vmImage: ubuntu-latest

lockBehavior: sequential

jobs:
  - deployment:
    environment: testenv
    strategy:
      runOnce:
        deploy:
          steps:
            - pwsh: Start-Sleep -Seconds 60
              displayName: sleep for 60 seconds
